// @ts-check
import js from '@eslint/js';
import tseslint from 'typescript-eslint';

/**
 * The one rule that carries real security weight here is `no-restricted-syntax`
 * on `process.env`. In a Next.js monolith the classic footgun is a secret
 * reaching the client bundle. We close it mechanically: packages/env is the
 * sole reader of process.env, everything else imports the validated object.
 */
const processEnvRule = {
  selector: "MemberExpression[object.object.name='process'][object.property.name='env']",
  message:
    'Do not read process.env directly. Import the validated config from @fluid/env — ' +
    'it is the single audited entry point for secrets.',
};

export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/.next/**',
      '**/dist/**',
      '**/generated/**',
      '**/*.config.js',
      '**/*.config.mjs',
      'scripts/**',
      // Generated by Next on every build; its triple-slash directives are not
      // ours to restyle.
      '**/next-env.d.ts',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/consistent-type-imports': [
        'error',
        { prefer: 'type-imports', fixStyle: 'inline-type-imports' },
      ],
      'no-restricted-syntax': ['error', processEnvRule],
    },
  },
  {
    // The one place allowed to read process.env.
    files: ['packages/env/src/**/*.ts'],
    rules: { 'no-restricted-syntax': 'off' },
  },
  {
    files: ['**/*.test.ts', '**/*.test.tsx', '**/test/**/*.ts'],
    rules: { '@typescript-eslint/no-explicit-any': 'off' },
  },
);
